###
POST http://localhost:8000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Juan Manuel",
    "lastname": "De Urquiza",
    "email": "juanmanuel@gmail.com",
    "password": "laloboton",
    "date": "2001-12-09"
}

###
GET http://localhost:8000/api/users HTTP/1.1

###
GET http://localhost:8000/api/users/ciriellifrancogiovanni@gmail.com HTTP/1.1

###
PUT http://localhost:8000/api/users/ciriellifrancogiovanni@gmail.com HTTP/1.1
Content-Type: application/json

{
    "name": "Franco Giovanni",
    "lastname": "Cirielli",
    "email": "ciriellifrancogiovanni@gmail.com",
    "password": "amoalostitotech",
    "date": "2002-09-12"
}
###
GET  http://localhost:8000/api/users/juancruzdeu@gmail.com HTTP/1.1

###
DELETE http://localhost:8000/api/users/663ba2bcaf2f47d8299c262f HTTP/1.1

###
POST http://localhost:8000/api/sucursales HTTP/1.1
Content-Type: application/json

{
    "nombre": "Sucursal 1",
    "ciudad": "La Plata",
    "calle": "8",
    "numero": 2515,
    "horarioApertura": "2024-05-14T08:00:00",
    "horarioCierre": "2024-05-14T20:00:00" 
}

###
GET http://localhost:8000/api/sucursales HTTP/1.1

###
DELETE http://localhost:8000/api/sucursales/666a11de728893f3336ff539 HTTP/1.1

###
GET http://localhost:8000/api/prodIntercambios HTTP/1.1

###
POST http://localhost:8000/api/prodIntercambios HTTP/1.1
Content-Type: application/json

{
    "titulo": "Martillo",
    "descripcion": "pega",
    "fotos": ["fotolocu"], 
    "categoria": "herramientas",
    "sucursal": "6643a558f1519bd16b0a6dc2",
    "inicioRango": "08:00",
    "finRango": "18:00",
    "idUsuario":"663d83bc15eaeb6d61fe62e2"
}
###
PUT http://localhost:8000/api/prodIntercambios/666871494a7c4961c35dab02 HTTP/1.1
Content-Type: application/json

{
    "estado": "libre"
}

###
DELETE http://localhost:8000/api/prodIntercambios/666a11de728893f3336ff539 HTTP/1.1
###
DELETE http://localhost:8000/api/eliminarTodosLosProductos HTTP/1.1

###
GET http://localhost:8000/api/filtrarProdIntercambios?sucursal=664a2a4b7b736ead28436ab5 HTTP/1.1

### 
GET http://localhost:8000/api/filtrarPropuestaIntercambios?nombreSucursal=Sucursal%20Los%20Horneros%20 HTTP/1.1

###
GET http://localhost:8000/api/propuestaIntercambio HTTP/1.1

###
GET http://localhost:8000/api/prodIntercambiosPorUsuario/juancruzdeu@gmail.com HTTP/1.1
###
GET http://localhost:8000/api/prodintercambios/664ce82ece3fb652d2ef09b1 HTTP/1.1

###
POST http://localhost:8000/api/empleados HTTP/1.1
Content-Type: application/json

{
    "nombre": "Marcos",
    "apellido": "Acuña",
    "dni": "27.352.578",
    "email": "marcos@ferreplus.com",
    "telefono": "221-5604567",
    "sucursal": "6643a558f1519bd16b0a6dc2"
}

###
GET http://localhost:8000/api/empleados HTTP/1.1

###
DELETE http://localhost:8000/api/empleados/cesar@ferreplus.com HTTP/1.1

###
GET http://localhost:8000/api/propuestaIntercambio HTTP/1.1

###
POST http://localhost:8000/api/propuestaIntercambio HTTP/1.1
Content-Type: application/json

{
    "productoOfrecido": "6656127e42daa5de01204e57",
    "productoDeseado": "664e071c47ac005b382963a2",
    "usuarioOfrecido": "ladislao",
    "usuarioDeseado": "franco",
    "nombreSucursal": "hrnos"
}

###
DELETE http://localhost:8000/api/eliminarTodosLosIntercambios HTTP/1.1

###
PUT http://localhost:8000/api/propuestaIntercambio/666a342e619be8d59fb739c8 HTTP/1.1
Content-Type: application/json

{
    "calificoOfrecido": false,
    "calificoDeseado": false

}



###
GET http://localhost:8000/api/filtrarPropuestaIntercambios?nombreSucursal="Sucursal Darío " HTTP/1.1
