###
POST http://localhost:8000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Juan Cruz",
    "lastname": "De Urquiza",
    "email": "juancruzdeu@gmail.com",
    "password": "laloboton",
    "date": "2001-12-09"
}

###
GET http://localhost:8000/api/users HTTP/1.1

###
GET http://localhost:8000/api/users/663ba2bcaf2f47d8299c262f HTTP/1.1

###
PUT http://localhost:8000/api/users/663ba2bcaf2f47d8299c262f HTTP/1.1
Content-Type: application/json

{
    "name": "Lautaro",
    "lastname": "Gutierrez",
    "email": "lautygutierrez5@gmail.com",
    "password": "candebordonmiamor",
    "date": "2001-06-06"
}


###
DELETE http://localhost:8000/api/users/663ba2bcaf2f47d8299c262f HTTP/1.1

###
POST http://localhost:8000/api/sucursales HTTP/1.1
Content-Type: application/json

{
    "nombre": "Sucursal 1",
    "ciudad": "La Plata",
    "calle": "8",
    "numero": 2515,
    "horarioApertura": "8:00",
    "horarioCierre": "20:00" 
}

###
GET http://localhost:8000/api/sucursales HTTP/1.1

###
DELETE http://localhost:8000/api/sucursales/663d83d115eaeb6d61fe62e4 HTTP/1.1