###
POST http://localhost:8000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Juan Manuel",
    "lastname": "De Urquiza",
    "email": "juanmanuel@gmail.com",
    "password": "laloboton",
    "date": "2001-12-09"
}

###
GET http://localhost:8000/api/users HTTP/1.1

###
GET http://localhost:8000/api/users/ciriellifrancogiovanni@gmail.com HTTP/1.1

###
PUT http://localhost:8000/api/users/ciriellifrancogiovanni@gmail.com HTTP/1.1
Content-Type: application/json

{
    "name": "Franco Giovanni",
    "lastname": "Cirielli",
    "email": "ciriellifrancogiovanni@gmail.com",
    "password": "amoalostitotech",
    "date": "2002-09-12"
}
###
GET  http://localhost:8000/api/users/juancruzdeu@gmail.com HTTP/1.1

###
DELETE http://localhost:8000/api/users/663ba2bcaf2f47d8299c262f HTTP/1.1

###
POST http://localhost:8000/api/sucursales HTTP/1.1
Content-Type: application/json

{
    "nombre": "Sucursal 1",
    "ciudad": "La Plata",
    "calle": "8",
    "numero": 2515,
    "horarioApertura": "2024-05-14T08:00:00",
    "horarioCierre": "2024-05-14T20:00:00" 
}

###
GET http://localhost:8000/api/sucursales HTTP/1.1

###
DELETE http://localhost:8000/api/sucursales/663d83d115eaeb6d61fe62e4 HTTP/1.1